services:
  postgres:
    image: postgres:17.4
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ~/challenge-atm-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
  api:
    build:
      context: .
      dockerfile: AtmChallenge.Api/Dockerfile
    container_name: atm_api_container
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQLConnection: "Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"
      - "8081:8081"
    profiles:
      - local
    
      
